import Head from 'next/head';
import { useState } from 'react';
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import {BsFillMoonStarsFill} from 'react-icons/Bs';
import Image from 'next/image';
import profilePic from '../public/Avatar.png';
import calculator from '../public/calculator.png';
import blackjack from '../public/blackjack.png';
import clickableSounds from '../public/clickableSounds.png';
import pairsGame from '../public/pairsGame.png';





export default function Home() {

  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Avatar.png" />
      </Head>

      <main className='px-10 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-4xl font-Rubik'>Portfolio</h1>
              <ul className='flex items-center gap-3'>
                <li>
                  <BsFillMoonStarsFill className='cursor-pointer text-l' />
                </li>
                <li>
                <a href='' className='bg-gradient-to-r from-purple-600 to-teal-500 rounded-md px-2 py-2'>Curriculum Vitae</a>
                </li>
              </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-br from-teal-600 to-purple-400 md:text-6xl">Simone Hassan</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Junior Front End Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-neutral-200 md:text-xl max-w-lg mx-auto'>
              Welcome to my Portfolio
            </p>
          </div>

          <div className='relative bg-gradient-to-b from-purple-500 rounded-full my-40 w-80 h-80 mt-20 overflow-hidden mx-auto'>
            <Image 
            src={profilePic}
            alt='Memoji myself'/>
          </div>

          <div className='text-5xl flex justify-center gap-5 py-3 bg-gradient-to-br from-teal-600 to-purple-400'>
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
        </section>

        <section>
          <div>
            <h3 className='py-5'></h3>
            <p className='text-md leading-1 text-zinc-100'>
              The beginning of my journey has amazing and difficult to following with the coding that 
              I am doing it for long time, I wonder why I did not think of doing coding when I was young.
              I am so glad to coming to inside of coding. I think that  the coding languages are awesome. 
            </p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg shadow-violet-700 p-10 rounded-xl my-10'>
              <h3 className='text-lg text-teal-300 font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
              Design or animate using an appropriate design style that is suited for your needs.
              </p>
              <h4 className='py-4 text-purple-300'><span>Designs tools I use</span></h4>
              <p className='text-zinc-100 py-1'>Canva</p>
              <p className='text-zinc-100 py-1'>Figma</p>
            </div>

  
            <div className='text-center shadow-lg shadow-violet-700 p-10 rounded-xl my-10'>
              <h3 className='text-lg text-teal-300 font-medium pt-8 pb-2'>Amazing Languages</h3>
              <p className='py-2'>
              Neat, understandable, easy code
              </p>
              <h4 className='py-4 text-purple-300'>The Languages I use</h4>
              <p className='text-zinc-100 py-1'>HTML</p>
              <p className='text-zinc-100 py-1'>CSS</p>
              <p className='text-zinc-100 py-1'>JavaScript</p>
              <p className='text-zinc-100 py-1'>NEXT/REACT.js</p>
              <p className='text-zinc-100 py-1'>Tailwind</p>
              <p className='text-zinc-100 py-1'>Bootstrap</p>
            </div>

            <div className='text-center shadow-lg shadow-violet-700 p-10 rounded-xl my-10'>
              <h3 className='text-lg text-teal-300 font-medium pt-8 pb-2'>Frameworks</h3>
              <p className='py-2'>
                Outside of those languages which I have other skills
              </p>
              <h4 className='py-4 text-purple-300'>The frameworks I use</h4>
              <p className='text-zinc-100 py-1'>GIT</p>
              <p className='text-zinc-100 py-1'>GITHUB</p>
              <p className='text-zinc-100 py-1'>NODE.js</p>
              <p className='text-zinc-100 py-1'>Microsoft Offics</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-2xl text-purple-400 py-1'>Projects</h3>
            <p>
            Here is my projects list:
            <li>Calculater</li>
            <li>Blackjack</li>
            <li>Clickable Sounds</li>
            <li>Pairs Game</li>
            
            I created with my existing skills.
            and I will learn more about full-stack development in the near future. I am always looking to learn more languages.
            Click on GitHub button to view the projects.
            </p>
          </div>
          
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>

            <div className='basic-1/3 flex-1'>
            <Image src={calculator} className='rounded-lg object-cover' width={'100%'} height={'100%'}
            alt='calculatorPicutre'/>
            </div>

            <div className='basic-1/3 flex-1'>
            <Image src={blackjack} className='rounded-lg object-cover' width={'100%'} height={'100%'}
            alt='blackjackPicture'/>
            </div>

            <div className='basic-1/3 flex-1'>
            <Image src={clickableSounds} className='rounded-lg object-cover' width={'100%'} height={'100%'}
            alt='clickableSoundsPicture'/>
            </div>

            <div className='basic-1/3 flex-1'>
            <Image src={pairsGame} className='rounded-lg object-cover' width={'100%'} height={'100%'}
            alt='pairsGamePicture'/>
            </div>

          </div>
        </section>

      </main>
    </div>
  )
}
